name: CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    name: Build (Python ${{ matrix.python-version }})
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install system dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y notmuch libnotmuch-dev
      - name: Install pypa/build and dependencies
        run: |
          # Install notmuch2 explicitly until weilbith/notmuch2-python-bindings#7 is fixed
          python3 -m pip install git+https://github.com/weilbith/notmuch2-python-bindings@69b50a0682a7c917bc0cd3bffd38efacf4f1679c --user
          python3 -m pip install build '.[doc,lint,test]' --user
      - name: flake8 lint
        run: |
          flake8 --ignore=E501,W504 afew/
      - name: Tests
        run: |
          pytest
      - name: Docs
        run: |
          sphinx-build -b html docs/ sphinx/html
          sphinx-build -b man docs/ sphinx/man
      - name: Store docs
        uses: actions/upload-artifact@v5
        with:
          name: docs
          path: sphinx/
