name: CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    name: Build (Python ${{ matrix.python-version }})
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install pypa/build and build-system deps
        run: |
          python3 -m pip install build setuptools setuptools_scm --user
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y notmuch libnotmuch-dev flake8
          python3 -m pip install pytest dkimpy flake8 git+https://github.com/weilbith/notmuch2-python-bindings@69b50a0682a7c917bc0cd3bffd38efacf4f1679c --user
      - name: flake8 lint
        run: |
          flake8 --ignore=E501,W504 afew/
      - name: Tests
        run: |
          python3 -m pip install freezegun --user
          pytest
