name: lint

on: push

jobs:
  build-ubuntu:
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    name: Build (Python ${{ matrix.python }})
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y notmuch python3-notmuch python3-venv flake8
          python3 -m venv env
          source ./env/bin/activate
          pip install setuptools pytest dkimpy
          ln -s /usr/lib/python3/dist-packages/notmuch ./env/lib/python*/site-packages
      - name: flake8
        run: |
          source ./env/bin/activate
          flake8 --ignore=E501,E701,E402,E129,E126,E711,E302,E251,E722,W503,E713,E401,F401,E303 afew/
